name: Run NodeJS

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading Spurt
        run: git clone  https://github.com/zer-far/spurt
      - name: Setting Up Spurt
        run: cd spurt && go get all && make
      - name: Downloading Repo
        run: git clone  https://github.com/cuma-kadal/new
      - name: Installing Package
        run: cd new && npm install
      - name: Running Bot
        run: cd new && npm start
