name: NodeJS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: time
        run: sudo timedatectl set-timezone Asia/Jakarta
      - name: Downloading Spurt
        run: git clone  https://github.com/zer-far/spurt
      - name: Setting Up Spurt
        run: cd spurt && go get all && make
      - name: Downloading Private Repo
        run: git clone https://cuma-kadal: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@github.com/cuma-kadal/new
      - name: Installing Package
        run: cd new && npm install
      - name: Running Bot
        run: cd new && npm start
